### ISSUE TITLE
Inconsistent decleration of event handlers

### ISSUE THREAD

**Issue by leolux** [jakearchibald/trained-to-thrill#18]
The way the event handlers for events like _install_ or _fetch_ are declerated are inconsistent between the official google developer documentation and this project:

`self.onfetch = function(event) {...}` vs. `self.addEventListener('fetch', function (event) {...}`

Why this inconsistency?

**Comment by jakearchibald** [comment]
The difference is the same between `el.onclick = func` and `el.addEventListener('click', func)`. The former is an event handler, and additional assignments will override the previous one, whereas the latter adds an event listener, and many of these can be added to the same object.

Since my code is the only code running in the service worker, it doesn't really matter which is used, but I tend to use `addEventListener` in more recent projects, like this:

```js
addEventListener('fetch', event => {
  // …
});
```

**Comment by leolux** [comment]
Ok, thanks!
